### ISSUE TITLE
Checklist on posting a salary

### ISSUE THREAD

**Issue by hossameldeen** [hossameldeen/transparent-salaries#6]
- [x] Taking salary-receiver's permission.
- [x] Consequences of writing a low salary in a company.
- [x] never deleted in beaker.
